spring.application.name=backend
server.port =80
server.servlet.context-path=/zaaricars/
spring.security.user.name=car
spring.security.user.password=car


#spring.datasource.url=jdbc:mysql://localhost:3306/zaari_cars?createDataBaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/zaari_cars
spring.datasource.username=Mohamed
spring.datasource.password=root


# Configuration de la connexion H2 (en memoire)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Activation et acces a console Web H2 (http://localhost:8080/h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true